package main

import (
	"crypto/tls"
	"errors"
	"fmt"
	"net/http"
	"regexp"
	"strings"

	. "c205.top/graduation"
	"github.com/gookit/color"
)

// net.DialTCP
// net.DialTimeout
// net.Dial

var s Set = Set{
	// "www.app.shopapi.xiaomi.com",
	"www.mail.xiaomi.com",
	"app.xiaomi.com",
	"haoda.xiaomi.com",
	"shenghuo.xiaomi.com",
	"dms.xiaomi.com",
	"ru-unlock.pt.intl.xiaomi.com",
	"b6.market.xiaomi.com",
	"www.f7.market.xiaomi.com",
	"staging1.tsmactivity.pay.xiaomi.com",
	"extranet.c3.qiye-pcdist.6nwxicuodr.elb.xiaomi.com",
	"apm.stage.pt.xiaomi.com",
	"cn.register.xmpush.xiaomi.com",
	"tj1.payment.pt.xiaomi.com",
	"api.hybrid.intl.xiaomi.com",
	"t.hd.xiaomi.com",
	"uaa.app-xae.xiaomi.com",
	"matrix.api.ad.xiaomi.com",
	"www.global.market.xiaomi.com",
	"hk.mibi.xiaomi.com",
	"staging.static.pay.xiaomi.com",
	"www.d.xiaomi.com",
	"www.staging.inform.idp.intl.xiaomi.com",
	"dushu.xiaomi.com",
	"www.us.iss.xiaomi.com",
	"www.zhuti.intl.xiaomi.com",
	"www.daily.i.xiaomi.com",
	"fe05.lg.xiaomi.com",
	"emq.xmpush.xiaomi.com",
	"internet.f75ba6adf0.elb.xiaomi.com",
	"admin-ssp.ad.xiaomi.com",
	"xms.be.xiaomi.com",
	"intranet.cn-beijing-6.youpinpc.vyw2cevgjy.elb.xiaomi.com",
	"internet.d7d6cdac68.elb.xiaomi.com",
	"www.zhuti.xiaomi.com",
	"bgp.data.game.xiaomi.com",
	"t.app.xiaomi.com",
	"www.tv.india.xiaomi.com",
	"s.pay.xiaomi.com",
	"center.hybrid.xiaomi.com",
	"www.w.pandora.xiaomi.com",
	"sfbweb.xiaomi.com",
	"cdn.fds.api.xiaomi.com",
	"feedback.pt.rus.xiaomi.com",
	"www.f8.market.xiaomi.com",
	"f10.market.xiaomi.com",
	"s008.iss.xiaomi.com",
	"extranet.c3.newdesigner-station.wlwzprvyuu.elb.xiaomi.com",
	"www.ru.api.xmpush.global.xiaomi.com",
	"www.c4.marathon.pt.xiaomi.com",
	"market.xiaomi.com",
	"profile.bee.mistat.intl.xiaomi.com",
	"www.device.account.xiaomi.com",
	"cnc.fe03.lg.xiaomi.com",
	"www.global.developer.xiaomi.com",
	"cdn.hao.xiaomi.com",
	"www.account.ai.xiaomi.com",
	"speech-sgp.ai.xiaomi.com",
	"hd.c3.f.mae.xiaomi.com",
	"git.xiaomi.com",
	"pan.xiaomi.com",
	"micro.game.xiaomi.com",
	"f7.market.xiaomi.com",
	"ru.feedback.xmpush.global.xiaomi.com",
	"bbs.mihome.xiaomi.com",
	"h5.tv.pandora.xiaomi.com",
	"open.ai.xiaomi.com",
	"api.xiaomi.com",
	"fe02.lg.xiaomi.com",
	"unlock.pt.xiaomi.com",
	"sd.lp.account.xiaomi.com",
	"www.f9.market.xiaomi.com",
	"intranet.c4.miui-l7-telecom.sd5pulwwuw.elb.xiaomi.com",
	"miuiapipay.xiaomi.com",
	"extranet.eu-east-1.miui-l7-middle.dwddxgqyqv.elb.xiaomi.com",
	"hm.xiaomi.com",
	"us.file.iss.xiaomi.com",
	"ctc.fe02.c3.xiaomi.com",
	"metok-ccc.intl.xiaomi.com",
	"bakctc.fe02.c3.xiaomi.com",
	"t14.market.xiaomi.com",
	"zhuomian.xiaomi.com",
	"ocean.pt.xiaomi.com",
	"t6.market.xiaomi.com",
	"creditcard.nfcpay.xiaomi.com",
	"staging.api.miui.security.xiaomi.com",
	"extranet.c4.miui-l7-vip.2tvizjzldf.elb.xiaomi.com",
	"video.xiaomi.com",
	"admin.xiaomi.com",
	"internet.d9f544dd0f.elb.xiaomi.com",
	"t4.market.xiaomi.com",
	"us.mixin.api.files.xiaomi.com",
	"mibi.stat.pt.xiaomi.com",
	"extranet.c3.tuishou-web.g7rz24sx5t.elb.xiaomi.com",
	"tj1.stagingouter.pay.xiaomi.com",
	"internet.883ee00748.elb.xiaomi.com",
	"lottery.recharge.pay.xiaomi.com",
	"preload.xiaomi.com",
	"c3.new.cname.recommend.pt.xiaomi.com",
	"internet.13e639f518.elb.xiaomi.com",
	"static.cdn.pandora.intl.xiaomi.com",
	"www.lottery.recharge.pay.xiaomi.com",
	"tv.india.xiaomi.com",
	"qiye.xiaomi.com",
	"internet.973277a51c.elb.xiaomi.com",
	"extranet.c3.tuishou-xiaomiyoupin-com.rcguqcslow.elb.xiaomi.com",
	"www.video.market.xiaomi.com",
	"www.static.account.xiaomi.com",
	"skype.xiaomi.com",
	"control.preload.xiaomi.com",
	"utility.recharge.pay.xiaomi.com",
	"static.oss.xiaomi.com",
	"global.video.intl.xiaomi.com",
	"api.developer.xiaomi.com",
	"h6.market.xiaomi.com",
	"mipop.xiaomi.com",
	"ai.api.xiaomi.com",
	"mf.xiaomi.com",
	"falcon.a.xiaomi.com",
	"www.storeconfig.mistat.xiaomi.com",
	"aemail.xiaomi.com",
	"extranet.c3.youyu-xiaomiyoupin-com.bpqaegltvk.elb.xiaomi.com",
	"hd.xiaomi.com",
	"meet.xiaomi.com",
	"sandbox.mibi.api.xiaomi.com",
	"awsbj0.fds.api.xiaomi.com",
	"www.matrix.api.ad.xiaomi.com",
	"wallet.pay.xiaomi.com",
	"tw.nlp.ai.xiaomi.com",
	"kong.bbs.xiaomi.com",
	"www.speech-preview.ai.xiaomi.com",
	"awsusor0-cdn.fds.api.xiaomi.com",
	"www.ssp.api.ad.xiaomi.com",
	"ppurifier.game.xiaomi.com",
	"cathro.in.pt.xiaomi.com",
	"intranet.c3.miui-l7-miuiauto.m5ccro85py.elb.xiaomi.com",
	"gw.pay.xiaomi.com",
	"extranet.c3.miui-l7-sec.bvxov9lmxj.elb.xiaomi.com",
	"m.zhuti.xiaomi.com",
	"intranet.c3.miui-l7-middle-lan.cq4bkn7ahg.elb.xiaomi.com",
	"static.mibi.xiaomi.com",
	"intranet.c4.miui-l7-feedback.dofgnunufz.elb.xiaomi.com",
	"m.xiaomi.com",
	"builder.pt.xiaomi.com",
	"www.canteen.pay.xiaomi.com",
	"internet.b09ad73cc3.elb.xiaomi.com",
	"www.track.ai.xiaomi.com",
	"onebox.xmpush.xiaomi.com",
	"www.fr.api.xmpush.global.xiaomi.com",
	"www.api.miui.security.xiaomi.com",
	"www.b2capipay.xiaomi.com",
	"id.video.intl.xiaomi.com",
	"extranet.c4.miui-l7-bsp-jupiter.ulwpesb1sj.elb.xiaomi.com",
	"abtest.mistat.india.xiaomi.com",
	"staging.adminbillprocess.mihome.intl.pt.xiaomi.com",
	"awssgp0-files.fds.api.xiaomi.com",
	"h3.market.xiaomi.com",
	"api.miui.security.xiaomi.com",
	"www.cdn.sysui.market.xiaomi.com",
	"events-prev.ai.xiaomi.com",
	"in.stagingcredit.pt.xiaomi.com",
	"www.iss.xiaomi.com",
	"www.api.account.xiaomi.com",
	"i.lg.api.xmpush.xiaomi.com",
	"intranet.cn-beijing-6.nginx-qa.uqlntg9yvw.elb.xiaomi.com",
	"intranet.c3.miui-l7-mistat-lan.sbjwz0vsrg.elb.xiaomi.com",
	"hao.xiaomi.com",
	"www.sandbox.xmpush.xiaomi.com",
	"hkmail.xiaomi.com",
	"staging2.tsmactivity.pay.xiaomi.com",
	"www.static.mibi.xiaomi.com",
	"api.mistat.xiaomi.com",
	"extranet.c3.cross-cloud.vjj4yk1h0h.elb.xiaomi.com",
	"autodiscover.xiaomi.com",
	"b2capi.pay.xiaomi.com",
	"internet.3988eba64b.elb.xiaomi.com",
	"sgp-l7-apm.slb.xiaomi.com",
	"internet.20c3e2d377.elb.xiaomi.com",
	"git.n.xiaomi.com",
	"hr.xiaomi.com",
	"mi.xiaomi.com",
	"metok.intl.xiaomi.com",
	"extranet.c3.miui-l7-sec.ppmucdjufw.elb.xiaomi.com",
	"extranet.c4.miui-l7-oto.facojgx9de.elb.xiaomi.com",
	"cnc.fe01.lg.xiaomi.com",
	"storeapi01.pay.xiaomi.com",
	"admin.bill.mihome.xiaomi.com",
	"api-preview.ai.xiaomi.com",
	"internet.dd895376a8.elb.xiaomi.com",
	"extranet.c3.shop-main.xhddc7bv3l.elb.xiaomi.com",
	"open.recommend.pt.xiaomi.com",
	"game.recharge.pay.xiaomi.com",
	"beta.hub.pf.xiaomi.com",
	"internet.5baa70e453.elb.xiaomi.com",
	"sds.api.xiaomi.com",
	"g8.cn.slb.xiaomi.com",
	"cname.maeproxy01.c3.public.xiaomi.com",
	"mvl7.pandora.xiaomi.com",
	"www.sd.lp.account.xiaomi.com",
	"f3.market.xiaomi.com",
	"www.i.xiaomi.com",
	"adminbill.mihome.intl.pt.xiaomi.com",
	"url8807.global.passport.xiaomi.com",
	"custom.zhuti.xiaomi.com",
	"www.gw.pay.xiaomi.com",
	"www.s008.iss.xiaomi.com",
	"extranet.c3.miui-l7-vip-xiaomi-cn.qcuw1esech.elb.xiaomi.com",
	"tw.api.ai.xiaomi.com",
	"extranet.ap-southeast-1.miui-l7-bsp-jupiter.01kgsgg7gs.elb.xiaomi.com",
	"staging.git.n.xiaomi.com",
	"www.dms.xiaomi.com",
	"mitools.pt.xiaomi.com",
	"d.xiaomi.com",
	"www.zhaoshang.shenghuo.xiaomi.com",
	"outbound.mxmail.xiaomi.com",
	"sso.pt.xiaomi.com",
	"mistat.intl.xiaomi.com",
	"extranet.c3.miui-l7-coreapp.okdovfsjm5.elb.xiaomi.com",
	"www.speech.ai.xiaomi.com",
	"extranet.ap-southeast-1.miui-l7-game.m4iioygtiw.elb.xiaomi.com",
	"h8.market.xiaomi.com",
	"tsmapi.pay.xiaomi.com",
	"miliao.migc.xiaomi.com",
	"web.music.xiaomi.com",
	"odm-builds.builder.pt.xiaomi.com",
	"admin.hybrid.xiaomi.com",
	"feedback.xmpush.xiaomi.com",
	"thm.market.intl.xiaomi.com",
	"www.gwpay.xiaomi.com",
	"www.speech-sgp.ai.xiaomi.com",
	"www.o2o.api.xiaomi.com",
	"www.mibi.xiaomi.com",
	"intranet.ap-southeast-1.miui-l7-middle-lan.w9t8zuamvy.elb.xiaomi.com",
	"secode2.hd.xiaomi.com",
	"f5.market.xiaomi.com",
	"awsbj0-cdn.fds-ssl.api.xiaomi.com",
	"matrix.avatar.ad.xiaomi.com",
	"www.lg.account.xiaomi.com",
	"pop3.xiaomi.com",
	"gl.cw.be.xiaomi.com",
	"zeus.ad.intl.xiaomi.com",
	"stats.xiaomi.com",
	"abtest.mistat.xiaomi.com",
	"app.shopapi.xiaomi.com",
	"zeus.ad.xiaomi.com",
	"www.sandbox.mibi.xiaomi.com",
	"internet.f63c402fcf.elb.xiaomi.com",
	"staging.cathro.in.pt.xiaomi.com",
	"register.xmpush.xiaomi.com",
	"cash.pay.xiaomi.com",
	"o2o.api.xiaomi.com",
	"www.i.api.xmpush.global.xiaomi.com",
	"hezi.xiaomi.com",
	"www.miuiapipay.xiaomi.com",
	"account.xiaomi.com",
	"yz.docker.pt.xiaomi.com",
	"wallpaper.pandora.xiaomi.com",
	"intranet.c4.miui-l7-miuiauto.ixil2qbsns.elb.xiaomi.com",
	"wtradv.market.xiaomi.com",
	"proxy.recharge.pay.xiaomi.com",
	"www.test.mi.pay.xiaomi.com",
	"testssp.api.ad.xiaomi.com",
	"storeconfig.mistat.xiaomi.com",
	"extranet.eu-east-1.miui-l7-feedback.fvlyh0lisv.elb.xiaomi.com",
	"www.api.mistat.xiaomi.com",
	"preview.mp.xiaomi.com",
	"www.quan.mis.migc.xiaomi.com",
	"www.lg.lp.account.xiaomi.com",
	"me.xiaomi.com",
	"miuirom.xiaomi.com",
	"www.drm.market.intl.xiaomi.com",
	"extranet.c3.developers-zhuti-pc.qnwxnaownq.elb.xiaomi.com",
	"www.mibi.api.xiaomi.com",
	"unlock.pt.intl.xiaomi.com",
	"o1.ptr6115.xiaomi.com",
	"www.staging.mipay.xiaomi.com",
	"hybrid.xiaomi.com",
	"intranet.ap-southeast-1.miui-l7-bsp-unlock.sktmfvvlrt.elb.xiaomi.com",
	"www.static.pay.xiaomi.com",
	"www.api.admob.xiaomi.com",
	"static.account.xiaomi.com",
	"www.sentry.pay.xiaomi.com",
	"share.mvideo.xiaomi.com",
	"test.e.ad.xiaomi.com",
	"staging.mipay.xiaomi.com",
	"logout.xiaomi.com",
	"10.xiaomi.com",
	"hk.mibi.api.xiaomi.com",
	"api.sdk.hybrid.xiaomi.com",
	"www.acheel.dmp.ad.xiaomi.com",
	"iauth.pt.xiaomi.com",
	"www.wap.phonerecharge.pay.xiaomi.com",
	"n.yunying.migc.xiaomi.com",
	"game2.recharge.pay.xiaomi.com",
	"exchange-dag1.xiaomi.com",
	"tv.intl.xiaomi.com",
	"www.sys.tv.india.xiaomi.com",
	"i.g3.cn.slb.xiaomi.com",
	"ctc.fe01.c3.xiaomi.com",
	"m.app.xiaomi.com",
	"www.weatherapi.market.xiaomi.com",
	"extranet.c4.miui-l7-sec.iydkpjbeca.elb.xiaomi.com",
	"video.market.xiaomi.com",
	"miuiapi.pay.xiaomi.com",
	"www.hao.xiaomi.com",
	"gjzwfw.hybrid.xiaomi.com",
	"feedback.pt.intl.xiaomi.com",
	"www.m.pay.xiaomi.com",
	"www.apitest.mibimagic.xiaomi.com",
	"file.cdn.mvideo.xiaomi.com",
	"www.gt.mo.intl.xiaomi.com",
	"extranet.c3.miui-l7-sec.msjhkem65f.elb.xiaomi.com",
	"www.file.cdn.mvideo.xiaomi.com",
	"www.pay.xiaomi.com",
	"bargain.staging.mifi.pt.xiaomi.com",
	"preview.market.n.xiaomi.com",
	"sf.pay.xiaomi.com",
	"globalvideo.cdn.pandora.intl.xiaomi.com",
	"www.storeapi01.pay.xiaomi.com",
	"gl.maf.be.xiaomi.com",
	"www.api.zhuti.intl.xiaomi.com",
	"www.fdsc3.iss.xiaomi.com",
	"www.game.recharge.pay.xiaomi.com",
	"weatherapi.intl.xiaomi.com",
	"coupon.center.pay.xiaomi.com",
	"g9.cn.slb.xiaomi.com",
	"www.vip.api.xmpush.xiaomi.com",
	"www.newcube.mifi.pt.xiaomi.com",
	"bk02.c3.xiaomi.com",
	"www.e.ad.xiaomi.com",
	"static.shenghuo.xiaomi.com",
	"extranet.c3.miui-l7-middle.nroxajo77s.elb.xiaomi.com",
	"www.web.recharge.pay.xiaomi.com",
	"intranet.c3.miui-l7-middle.bagrakz6gd.elb.xiaomi.com",
	"storegw02.pay.xiaomi.com",
	"internet.e773e59af8.elb.xiaomi.com",
	"sip.xiaomi.com",
	"cn.app-xae.xiaomi.com",
	"bk01.hh.xiaomi.com",
	"5-c3.b2cop.bgp.neo.xiaomi.com",
	"sandbox.billapi.xiaomi.com",
	"api.chat.cname.xiaomi.com",
	"www.sdkconfig.ad.xiaomi.com",
	"extranet.c4.miui-l7-miuiauto.bcmmezkwb9.elb.xiaomi.com",
	"feedback.xmpush.global.xiaomi.com",
	"controller.india.xiaomi.com",
	"g.o2o.hybrid.xiaomi.com",
	"www.s.pay.xiaomi.com",
	"superset.preload.xiaomi.com",
	"test.mae.xiaomi.com",
	"www.tw.api.ai.xiaomi.com",
	"extranet.c3.cps-youyu-xiaomiyoupin-com.1awdodcbjk.elb.xiaomi.com",
	"b.pay.xiaomi.com",
	"redmine.xiaomi.com",
	"c3.ai.xiaomi.com",
	"apps.xiaomi.com",
	"www.api.ai.xiaomi.com",
	"order.music.xiaomi.com",
	"intranet.c3.miui-l7-middle.8hstz0pgrm.elb.xiaomi.com",
	"www.s010.iss.xiaomi.com",
	"video.in.intl.xiaomi.com",
	"z.www.xiaomi.com",
	"extranet.c3.youpinpc.cc1eyyxtrl.elb.xiaomi.com",
	"igame.xiaomi.com",
	"wms.be.xiaomi.com",
	"drm.market.xiaomi.com",
	"hd.account.xiaomi.com",
	"www.tsmapi.pay.xiaomi.com",
	"a0.app.xiaomi.com",
	"cloudml.api.xiaomi.com",
	"tms.be.xiaomi.com",
	"wiki.dev.xiaomi.com",
	"cdn.sysui.market.xiaomi.com",
	"debug.max.ad.xiaomi.com",
	"www.app.market.xiaomi.com",
	"lg.api.xmpush.xiaomi.com",
	"adminbillprocess.mihome.intl.pt.xiaomi.com",
	"www.dev.xiaomi.com",
	"eid.nfcpay.xiaomi.com",
	"extranet.c3.miui-l7-data-test.cllegj9qtj.elb.xiaomi.com",
	"sandbox.xmpush.xiaomi.com",
	"f6.market.xiaomi.com",
	"files.ai.xiaomi.com",
	"chat.kefu.xiaomi.com",
	"in-unlock.pt.intl.xiaomi.com",
	"eb.hybrid.xiaomi.com",
	"h9.market.xiaomi.com",
	"www.api.xmpush.global.xiaomi.com",
	"www.hd.account.xiaomi.com",
	"internet.488b649984.elb.xiaomi.com",
	"tel.fe01.hh.xiaomi.com",
	"e.ad.xiaomi.com",
	"api.account.xiaomi.com",
	"www.emq.xmpush.xiaomi.com",
	"storegw01.pay.xiaomi.com",
	"www.dav.xiaomi.com",
	"global.account.xiaomi.com",
	"promo.xiaomi.com",
	"b2capipay.xiaomi.com",
	"c3.bgp.big.mae.xiaomi.com",
	"invideo.cdn.pandora.intl.xiaomi.com",
	"www.game2.recharge.pay.xiaomi.com",
	"bgp.cdn.c3.xiaomi.com",
	"intl.profile.ad.xiaomi.com",
	"ime.api.xiaomi.com",
	"api.music.xiaomi.com",
	"api.admob.xiaomi.com",
	"jubao.order.xiaomi.com",
	"extranet.c3.miui-l7-dsg.r2uy5hfqwv.elb.xiaomi.com",
	"fds-ssl.api.xiaomi.com",
	"dev.xiaomi.com",
	"www.staging.static.pay.xiaomi.com",
	"order.xiaomi.com",
	"extranet.c3.miui-l7-global.rkewv7fopu.elb.xiaomi.com",
	"c3.api.xmpush.xiaomi.com",
	"autodiscover.v.xiaomi.com",
	"staging.api.mipay.xiaomi.com",
	"www.account.xiaomi.com",
	"xiazai.xiaomi.com",
	"test.zeus.ad.xiaomi.com",
	"awsbj0-files.fds.api.xiaomi.com",
	"www.wtradv.market.xiaomi.com",
	"internet.0e8a25caee.elb.xiaomi.com",
	"www.xiaomi.com",
	"i.xiaomi.com",
	"www.sandbox.mibi.api.xiaomi.com",
	"www.data.mistat.xiaomi.com",
	"land.cname.xiaomi.com",
	"www.storeapi02.pay.xiaomi.com",
	"www.data.mistat.intl.xiaomi.com",
	"fr.feedback.xmpush.global.xiaomi.com",
	"us.iss.xiaomi.com",
	"ru.api.xmpush.global.xiaomi.com",
	"internet.301d8b5074.elb.xiaomi.com",
	"ofile.market.xiaomi.com",
	"www.stat.pay.xiaomi.com",
	"apitest.mibimagic.xiaomi.com",
	"data.game.xiaomi.com",
	"tsmadmin.pt.xiaomi.com",
	"coml7.pandora.xiaomi.com",
	"internet.9a2e623cf7.elb.xiaomi.com",
	"www.shop.pandora.xiaomi.com",
	"www.api-preview.ai.xiaomi.com",
	"data.mistat.xiaomi.com",
	"mitunes.game.xiaomi.com",
	"exp.api.xiaomi.com",
	"internet.8d57221dd5.elb.xiaomi.com",
	"designer.xiaomi.com",
	"sys.tv.india.xiaomi.com",
	"file.market.xiaomi.com",
	"activity.hybrid.xiaomi.com",
	"www.appwall.ad.intl.xiaomi.com",
	"www.hm.xiaomi.com",
	"static.game.xiaomi.com",
	"dialin.xiaomi.com",
	"www.mds.mistat.xiaomi.com",
	"comc4l7.pandora.xiaomi.com",
	"test.mi.pay.xiaomi.com",
	"bridge.kefu.xiaomi.com",
	"extranet.c3.miui-l7-coreapp.ugabkyywhq.elb.xiaomi.com",
	"storeconfig.mistat.intl.xiaomi.com",
	"dav.xiaomi.com",
	"controller.intl.xiaomi.com",
	"intranet.cn-beijing-6.miui-l7-middle.tlo5pyqnxx.elb.xiaomi.com",
	"www.storegw01.pay.xiaomi.com",
	"mxhk.mxmail.xiaomi.com",
	"actfile.cdn.pandora.xiaomi.com",
	"chaxun.xiaomi.com",
	"zhuti.designer.xiaomi.com",
	"www.sandbox.billapi.xiaomi.com",
	"extranet.c3.miui-l7-miuiauto.0bdzkgvi8u.elb.xiaomi.com",
	"rugw.pay.xiaomi.com",
	"gl.xms.be.xiaomi.com",
	"theme.xiaomi.com",
	"mp.xiaomi.com",
	"docs.api.xiaomi.com",
	"www.my.xiaomi.com",
	"staging.mifi.pt.xiaomi.com",
	"billapi.xiaomi.com",
	"www.hh.lp.account.xiaomi.com",
	"www.video.intl.xiaomi.com",
	"internet.efe7f7274c.elb.xiaomi.com",
	"gt.mo.intl.xiaomi.com",
	"internet.59b55fab13.elb.xiaomi.com",
	"contract.shopapi.xiaomi.com",
	"extranet.ap-southeast-1.miui-l7-middle.flhmv7hsdq.elb.xiaomi.com",
	"h1.market.xiaomi.com",
	"pay.xiaomi.com",
	"internet.05a8222ea8.elb.xiaomi.com",
	"feedback.pt.xiaomi.com",
	"t2.market.xiaomi.com",
	"lyncdiscover.xiaomi.com",
	"falcon.pt.xiaomi.com",
	"extranet.c3.youpin-merchantdist.ew3g0prurn.elb.xiaomi.com",
	"gwpay.xiaomi.com",
	"c3.pandora.xiaomi.com",
	"secdb.pt.xiaomi.com",
	"cnbj2.fds.api.xiaomi.com",
	"ccg.migc.xiaomi.com",
	"idmb.register.xmpush.global.xiaomi.com",
	"register.xmpush.global.xiaomi.com",
	"cms.nfcpay.xiaomi.com",
	"images.cdn.pt.xiaomi.com",
	"zhaoshang.shenghuo.xiaomi.com",
	"tongji.d.pt.xiaomi.com",
	"canteen.pay.xiaomi.com",
	"spf_bj.mxmail.xiaomi.com",
	"c3.ctc.mae.xiaomi.com",
	"www.storeconfig.mistat.intl.xiaomi.com",
	"speech-preview.ai.xiaomi.com",
	"mixin.api.files.xiaomi.com",
	"www.storegw02.pay.xiaomi.com",
	"extranet.c3.miui-l7-global.cgsruzszgl.elb.xiaomi.com",
	"be.xiaomi.com",
	"quan.mis.migc.xiaomi.com",
	"yingyong.xiaomi.com",
	"api.xmpush.xiaomi.com",
	"nlp.ai.xiaomi.com",
	"extranet.c3.content-platform.xkq8jtxhkr.elb.xiaomi.com",
	"lp.account.xiaomi.com",
	"olap.api.xiaomi.com",
	"mis.migc.xiaomi.com",
	"www.hk.mibi.api.xiaomi.com",
	"www.fr.feedback.xmpush.global.xiaomi.com",
	"internet.6b2b6aa4cf.elb.xiaomi.com",
	"staging.adminbill.mihome.intl.pt.xiaomi.com",
	"app.market.xiaomi.com",
	"internet.27b9718cd5.elb.xiaomi.com",
	"thm.market.xiaomi.com",
	"in.o2o.api.xiaomi.com",
	"bi.migc.xiaomi.com",
	"s010.iss.xiaomi.com",
	"www.skype.xiaomi.com",
	"www.insight.ad.xiaomi.com",
	"r2.ai.xiaomi.com",
	"staging.inform.idp.intl.xiaomi.com",
	"staging.m.pay.xiaomi.com",
	"global.developer.xiaomi.com",
	"assistant.pandora.xiaomi.com",
	"sys.intl.xiaomi.com",
	"sg.buy.be.xiaomi.com",
	"static.hybrid.xiaomi.com",
	"mx1.mxmail.xiaomi.com",
	"quality.ate.n.xiaomi.com",
	"intranet.ap-southeast-1.miui-l7-middle-lan.ef2xnasxbe.elb.xiaomi.com",
	"staging.ai.api.xiaomi.com",
	"ot.owms.api.xiaomi.com",
	"m.pay.xiaomi.com",
	"hysdk.game.xiaomi.com",
	"extranet.c3.node-operation.yr31avgjbz.elb.xiaomi.com",
	"smtp.xiaomi.com",
	"union.xiaomi.com",
	"t3.market.xiaomi.com",
	"www.sf.pay.xiaomi.com",
	"www.cdns.fds.api.xiaomi.com",
	"outboundhk.mxmail.xiaomi.com",
	"preview.auto.pt.xiaomi.com",
	"9-alisgp.i18n.pub.neo.xiaomi.com",
	"bbs.game.xiaomi.com",
	"preview.api.game.hybrid.xiaomi.com",
	"intranet.c3.miui-l7-mistat-lan.wfhktin0qe.elb.xiaomi.com",
	"m.video.xiaomi.com",
	"www.hk.mibi.xiaomi.com",
	"vca.ai.xiaomi.com",
	"www.order.music.xiaomi.com",
	"cms.api.music.xiaomi.com",
	"www.recharge.pay.xiaomi.com",
	"bgp.c3.big.mae.xiaomi.com",
	"xitong.xiaomi.com",
	"m.mibi.xiaomi.com",
	"internet.275706773e.elb.xiaomi.com",
	"cs.be.xiaomi.com",
	"speech.ai.xiaomi.com",
	"xiaomi.com",
	"www.globalapi.ad.xiaomi.com",
	"datum.xiaomi.com",
	"hd02.lg.xiaomi.com",
	"userid.xiaomi.com",
	"tw.xiaomi.com",
	"preloadpm.xiaomi.com",
	"i.api.xmpush.global.xiaomi.com",
	"www.sec.xiaomi.com",
	"cnbj2.vision.api.xiaomi.com",
	"www.intl.profile.ad.xiaomi.com",
	"heyue.xiaomi.com",
	"www.s.passbook.xiaomi.com",
	"api.kuai.mvideo.xiaomi.com",
	"staging.tsmactivity.pay.xiaomi.com",
	"lg.lp.account.xiaomi.com",
	"www.nlp-preview.ai.xiaomi.com",
	"test.ad.intl.xiaomi.com",
	"ics-oms.ai.xiaomi.com",
	"infosec.xiaomi.com",
	"idmb.api.xmpush.global.xiaomi.com",
	"api.hybrid.xiaomi.com",
	"static.verify.sec.xiaomi.com",
	"staging-admin-ssp.ad.xiaomi.com",
	"m.hk.mibi.xiaomi.com",
	"cname.maeproxy01.lg.public.xiaomi.com",
	"sec.xiaomi.com",
	"passbook.xiaomi.com",
	"f4.market.xiaomi.com",
	"extranet.c3.miui-l7-vip.4iurt3sqql.elb.xiaomi.com",
	"bgp.g0.cn.slb.xiaomi.com",
	"www.thm.market.xiaomi.com",
	"c3.tomato.agent.mifi.pt.xiaomi.com",
	"www.f6.market.xiaomi.com",
	"imp.xmpush.xiaomi.com",
	"mipop.bbs.xiaomi.com",
	"mx2.account.xiaomi.com",
	"extranet.c3.miui-l7-mina.6zfayeoaab.elb.xiaomi.com",
	"www.test.ad.intl.xiaomi.com",
	"ga.mo.intl.xiaomi.com",
	"extranet.c3.miui-l7-global-online.nb5xhk0x4c.elb.xiaomi.com",
	"sys.tv.idn.xiaomi.com",
	"backend.xiaomi.com",
	"inapi.pay.xiaomi.com",
	"appwall.ad.intl.xiaomi.com",
	"contents.api.xiaomi.com",
	"internet.1e9aad09a8.elb.xiaomi.com",
	"www.exp.api.xiaomi.com",
	"extranet.ap-southeast-1.ngx-gameunion-ocean.xvtznfgdy6.elb.xiaomi.com",
	"gb.comm.pt.xiaomi.com",
	"internet.4037981c85.elb.xiaomi.com",
	"open.content.pt.xiaomi.com",
	"ruapi.pay.xiaomi.com",
	"api.ad.intl.xiaomi.com",
	"passport.keytool.pt.xiaomi.com",
	"device.account.xiaomi.com",
	"developer.xiaomi.com",
	"blog.xiaomi.com",
	"wiki.designer.xiaomi.com",
	"mail.xiaomi.com",
	"g.pandora.xiaomi.com",
	"zhuti.xiaomi.com",
	"www.xms.be.xiaomi.com",
	"insight.ad.xiaomi.com",
	"www.staging.api.mipay.xiaomi.com",
	"internet.6d9652a67f.elb.xiaomi.com",
	"www.api.hybrid.xiaomi.com",
	"extranet.c3.miui-l7-oto.kyrnnxezzo.elb.xiaomi.com",
	"mitu.xiaomi.com",
	"extranet.c3.miui-l7-bsp-jupiter.utqyy6it4x.elb.xiaomi.com",
	"dev.sso.pt.xiaomi.com",
	"h2.market.xiaomi.com",
	"galleryl7.pandora.xiaomi.com",
	"tj1.staging.pay.xiaomi.com",
	"sdkconfig.ad.xiaomi.com",
	"marmot.pt.xiaomi.com",
	"a.stat.xiaomi.com",
	"www.mis.migc.xiaomi.com",
	"www.secure.report.iss.xiaomi.com",
	"sdkconfig.ad.intl.xiaomi.com",
	"mail.v.xiaomi.com",
	"o2o.hybrid.xiaomi.com",
	"www.api.ad.xiaomi.com",
	"huosai.xiaomi.com",
	"drm.market.intl.xiaomi.com",
	"c3.ctc.big.mae.xiaomi.com",
	"api.dp.pt.xiaomi.com",
	"www.api.developer.xiaomi.com",
	"api.passbook.xiaomi.com",
	"hk.xiaomi.com",
	"h7.market.xiaomi.com",
	"extranet.c3.youpin-nginx-openapi.pbbogoq0i4.elb.xiaomi.com",
	"yz.marathon.v1.pt.xiaomi.com",
	"zhuti.intl.xiaomi.com",
	"extranet.c3.h2-test.3zegfibvfy.elb.xiaomi.com",
	"hh.lp.account.xiaomi.com",
	"www.sysui.market.xiaomi.com",
	"imap.xiaomi.com",
	"bk01.c3.xiaomi.com",
	"zhushou.xiaomi.com",
	"img.cdn.mvideo.xiaomi.com",
	"cnbj2.cloudml.api.xiaomi.com",
	"tw.speech.ai.xiaomi.com",
	"gallery.cdn.pandora.xiaomi.com",
	"daily.i.xiaomi.com",
	"api.zhuti.intl.xiaomi.com",
	"h5.market.xiaomi.com",
	"extranet.c3.nginx-production.njmvwkenhx.elb.xiaomi.com",
	"www.share.mvideo.xiaomi.com",
	"www.api.xmpush.xiaomi.com",
	"www.sds.api.xiaomi.com",
	"stats.api.hybrid.xiaomi.com",
	"ocean.staging.pt.xiaomi.com",
	"sysui.market.xiaomi.com",
	"www.api.zhuti.xiaomi.com",
	"www.push.a.xiaomi.com",
	"admin.xmpush.xiaomi.com",
	"www.hk.billapi.xiaomi.com",
	"web.recharge.pay.xiaomi.com",
	"ssp.api.ad.xiaomi.com",
	"talos.api.xiaomi.com",
	"static.union.xiaomi.com",
	"ins.admin.pt.xiaomi.com",
	"bss.pandora.xiaomi.com",
	"www.cnbj2.vision.api.xiaomi.com",
	"music.xiaomi.com",
	"cathro.id.pt.xiaomi.com",
	"www.ru.register.xmpush.global.xiaomi.com",
	"iss.xiaomi.com",
	"cdn-thumb.fds.api.xiaomi.com",
	"oss.xiaomi.com",
	"api.xmpush.global.xiaomi.com",
	"weatherapi.market.xiaomi.com",
	"aipa.ai.xiaomi.com",
	"minet.pt.xiaomi.com",
	"mds.mistat.xiaomi.com",
	"preview.api.zhuti.n.xiaomi.com",
	"bgp.g1.cn.slb.xiaomi.com",
	"sign1.n.xiaomi.com",
	"push.a.xiaomi.com",
	"jellyfish.pandora.xiaomi.com",
	"internet.80fb1a5a9e.elb.xiaomi.com",
	"cnbj0.fds.api.xiaomi.com",
	"www.passbook.xiaomi.com",
	"ru.register.xmpush.global.xiaomi.com",
	"www.b.pay.xiaomi.com",
	"wl.voip.game.xiaomi.com",
	"www.nlp.ai.xiaomi.com",
	"data.mistat.rus.xiaomi.com",
	"tw.account.ai.xiaomi.com",
	"www.ru.feedback.xmpush.global.xiaomi.com",
	"www.designer.xiaomi.com",
	"www.zeus.ad.intl.xiaomi.com",
	"www.proxy.recharge.pay.xiaomi.com",
	"extranet.c3.ecod-fe.stpmtdl1mf.elb.xiaomi.com",
	"fe01.lg.xiaomi.com",
	"fm.web.music.xiaomi.com",
	"mibi.xiaomi.com",
	"abtest.mistat.intl.xiaomi.com",
	"query-suggestion-preview.ai.xiaomi.com",
	"api.ai.xiaomi.com",
	"peijian.xiaomi.com",
	"www.staging.ai.api.xiaomi.com",
	"www.ac.account.xiaomi.com",
	"i18n.mae.xiaomi.com",
	"t3.a.market.xiaomi.com",
	"relay.xiaomi.com",
	"www.falcon.a.xiaomi.com",
	"tj1.staging-in.globalfi.pt.xiaomi.com",
	"gl.mal.be.xiaomi.com",
	"www.sgp.o2o.api.xiaomi.com",
	"vip.api.xmpush.global.xiaomi.com",
	"video.intl.xiaomi.com",
	"intranet.eu-east-1.miui-l7-feedback.riqqugwspr.elb.xiaomi.com",
	"w.pandora.xiaomi.com",
	"qabot-openbase.ai.xiaomi.com",
	"i.fr.api.xmpush.global.xiaomi.com",
	"g6.cn.slb.xiaomi.com",
	"preview.zhuti.n.xiaomi.com",
	"www.thm.market.intl.xiaomi.com",
	"extranet.c3.miui-l7-miuiauto.tflctwn2t6.elb.xiaomi.com",
	"preview.open.game.hybrid.xiaomi.com",
	"www.a0.app.xiaomi.com",
	"track.ai.xiaomi.com",
	"extranet.c3.miui-l7-feedback.1irknwwveg.elb.xiaomi.com",
	"extranet.c4.miui-l7-bsp-unlock.dz9juywbpp.elb.xiaomi.com",
	"extranet.c3.mimc-admin.pkqygosv1j.elb.xiaomi.com",
	"enfile.market.xiaomi.com",
	"www.us.file.iss.xiaomi.com",
	"www.ot.owms.api.xiaomi.com",
	"fr.register.xmpush.global.xiaomi.com",
	"milink.pandora.xiaomi.com",
	"intranet.ap-southeast-1.miui-l7-middle.xf0rzuab4j.elb.xiaomi.com",
	"bgp.fe01.c3.xiaomi.com",
	"newcube.mifi.pt.xiaomi.com",
	"bbs.xiaomi.com",
	"www.contents.api.xiaomi.com",
	"cdn.pt.xiaomi.com",
	"www.gl.xms.be.xiaomi.com",
	"www.api.pay.xiaomi.com",
	"www.dp.pt.xiaomi.com",
	"www.lp.account.xiaomi.com",
	"extranet.c3.nginx-youpinpromotion.g6nx3pmfjy.elb.xiaomi.com",
	"www.b2capi.pay.xiaomi.com",
	"h4.market.xiaomi.com",
	"product.xiaomi.com",
	"bar.xiaomi.com",
	"extranet.c3.miui-l7-vip-xiaomi-cn.ic5znxsxzb.elb.xiaomi.com",
	"www.ime.api.xiaomi.com",
	"www.ga.mo.intl.xiaomi.com",
	"jira.n.xiaomi.com",
	"bakctc.fe01.c3.xiaomi.com",
	"assistant.api.xiaomi.com",
	"c1.b.mae.xiaomi.com",
	"www.iauth.pt.xiaomi.com",
	"ident.mistat.xiaomi.com",
	"webapp.xiaomi.com",
	"tw.file.ai.xiaomi.com",
	"www.c3.api.xmpush.xiaomi.com",
	"emr.api.xiaomi.com",
	"www.test.zeus.ad.xiaomi.com",
	"comc5l7.pandora.xiaomi.com",
	"www.file.ai.xiaomi.com",
	"www.miuiapi.pay.xiaomi.com",
	"internet.d20a1fb131.elb.xiaomi.com",
	"staging.cathro.id.pt.xiaomi.com",
	"www.tsmactivity.pay.xiaomi.com",
	"kefu.xiaomi.com",
	"recharge.pay.xiaomi.com",
	"bgp.zhuti.xiaomi.com",
	"staging.api.idp.intl.xiaomi.com",
	"extranet.c3.cooperation-pcdist.fnubts1bff.elb.xiaomi.com",
	"s.passbook.xiaomi.com",
	"mx1.account.xiaomi.com",
	"weixin.cdn.pandora.xiaomi.com",
	"shop.pandora.xiaomi.com",
	"www.ai.api.xiaomi.com",
	"www.stat.file.market.xiaomi.com",
	"staging3.tsmactivity.pay.xiaomi.com",
	"tv.idn.xiaomi.com",
	"events.ai.xiaomi.com",
	"docker.pt.xiaomi.com",
	"h0.market.xiaomi.com",
	"ac.account.xiaomi.com",
	"www.assistant.api.xiaomi.com",
	"bk01.lg.xiaomi.com",
	"kds.market.xiaomi.com",
	"www.open.account.xiaomi.com",
	"fuwu.xiaomi.com",
	"staging.tsmadmin.pt.xiaomi.com",
	"test.api.xmpush.xiaomi.com",
	"vip.api.xmpush.xiaomi.com",
	"bulldog.pt.xiaomi.com",
	"t5.market.xiaomi.com",
	"wap.phonerecharge.pay.xiaomi.com",
	"my.xiaomi.com",
	"query-suggestion.ai.xiaomi.com",
	"c4.marathon.pt.xiaomi.com",
	"internet.4d2bb010ad.elb.xiaomi.com",
	"stat.pay.xiaomi.com",
	"www.open.ai.xiaomi.com",
	"f8.market.xiaomi.com",
	"p.www.xiaomi.com",
	"storeapi02.pay.xiaomi.com",
	"share.xiaomi.com",
	"derora.api.xiaomi.com",
	"f2.market.xiaomi.com",
	"globalapi.ad.xiaomi.com",
	"www.market.xiaomi.com",
	"www.fr.register.xmpush.global.xiaomi.com",
	"mx3.mxmail.xiaomi.com",
	"feedback.d.xiaomi.com",
	"fdsc3.iss.xiaomi.com",
	"www.api.hybrid.intl.xiaomi.com",
	"www.register.xmpush.global.xiaomi.com",
	"fr.api.xmpush.global.xiaomi.com",
	"admin.migc.xiaomi.com",
	"www.api.d.xiaomi.com",
	"ssp.xiaomi.com",
	"tsmactivity.pay.xiaomi.com",
	"www.register.xmpush.xiaomi.com",
	"misc.pandora.xiaomi.com",
	"www.infosec.xiaomi.com",
	"data.mistat.intl.xiaomi.com",
	"www.utility.recharge.pay.xiaomi.com",
	"smsapi.notify.xiaomi.com",
	"secure.report.iss.xiaomi.com",
	"extern.sso.pt.xiaomi.com",
	"userright.ai.xiaomi.com",
	"www.admin.hybrid.xiaomi.com",
	"www.feedback.xmpush.global.xiaomi.com",
	"api.pay.xiaomi.com",
	"job.xiaomi.com",
	"staging.nfcpay.xiaomi.com",
	"i.c3.api.xmpush.xiaomi.com",
	"www.api.xiaomi.com",
	"www.zeus.ad.xiaomi.com",
	"staging.mitools.pt.xiaomi.com",
	"huodong.xiaomi.com",
	"ad.intl.xiaomi.com",
	"ru.o2o.api.xiaomi.com",
	"admin.report.pt.xiaomi.com",
	"app.migc.xiaomi.com",
	"static.haoda.xiaomi.com",
	"emq.api.xiaomi.com",
	"ccc.sys.intl.xiaomi.com",
	"g4.cn.slb.xiaomi.com",
	"www.profile.bee.mistat.xiaomi.com",
	"vca-prev.ai.xiaomi.com",
	"www.f10.market.xiaomi.com",
	"global.market.xiaomi.com",
	"ottl7.pandora.xiaomi.com",
	"mibi.api.xiaomi.com",
	"hk.billapi.xiaomi.com",
	"translator.pandora.xiaomi.com",
	"account.ai.xiaomi.com",
	"www.api.ad.intl.xiaomi.com",
	"lcs.api.xiaomi.com",
	"open.account.xiaomi.com",
	"extranet.c4.compass-admin.fmaoy4mrqk.elb.xiaomi.com",
	"cnbj1.fds.api.xiaomi.com",
	"boss.mvideo.xiaomi.com",
	"dp.pt.xiaomi.com",
	"notice.game.xiaomi.com",
	"game.xiaomi.com",
	"sdkconfig.ad.india.xiaomi.com",
	"ingw.pay.xiaomi.com",
	"wan.xiaomi.com",
	"www.m.hk.mibi.xiaomi.com",
	"cdns.fds.api.xiaomi.com",
	"www.billapi.xiaomi.com",
	"metrics.api.xiaomi.com",
	"profile.bee.mistat.xiaomi.com",
	"c1.f.mae.xiaomi.com",
	"sandbox.mibi.xiaomi.com",
	"static.pay.xiaomi.com",
	"internet.cbf3ef0c6d.elb.xiaomi.com",
	"extranet.c3.youpin-nginx-data.0fzho9yfzw.elb.xiaomi.com",
	"internet.31cae9ccf4.elb.xiaomi.com",
	"www.m.mibi.xiaomi.com",
	"fds.api.xiaomi.com",
	"www.api.passbook.xiaomi.com",
	"p.xiaomi.com",
	"extranet.c3.online-support.mj2o8fpfeb.elb.xiaomi.com",
	"bjmail.xiaomi.com",
	"t1.market.xiaomi.com",
	"api.designer.xiaomi.com",
	"speech-tw.ai.xiaomi.com",
	"f9.market.xiaomi.com",
	"acheel.dmp.ad.xiaomi.com",
	// "sdkconfig.ad.rus.xiaomi.com",
	// "file.ai.xiaomi.com",
	// "f1.market.xiaomi.com",
	// "gw8.pay.xiaomi.com",
	// "preview.platform.game.hybrid.xiaomi.com",
	// "www.feedback.xmpush.xiaomi.com",
	// "www.static.hybrid.xiaomi.com",
	// "ecoprj.xiaomi.com",
	// "sentry.pay.xiaomi.com",
	// "hd01.lg.xiaomi.com",
	// "www.shenghuo.xiaomi.com",
	// "g7.cn.slb.xiaomi.com",
	// "ecom.intl.xiaomi.com",
	// "www.static.shenghuo.xiaomi.com",
	// "data.mistat.india.xiaomi.com",
	// "api.zhuti.xiaomi.com",
	// "callback.xmpush.xiaomi.com",
	// "speech.xiaomi.com",
	// "api.ad.xiaomi.com",
	// "api.d.xiaomi.com",
	// "admin.xmpush.global.xiaomi.com",
	// "sgp.o2o.api.xiaomi.com",
	// "push.o2o.api.xiaomi.com",
	// "www.profile.bee.mistat.intl.xiaomi.com",
	// "staging.data.game.xiaomi.com",
	// "nlp-preview.ai.xiaomi.com",
	// "www.files.ai.xiaomi.com",
	// "idmb.feedback.xmpush.global.xiaomi.com",
	// "stat.file.market.xiaomi.com",
	// "lg.account.xiaomi.com",
	// "www.callback.xmpush.xiaomi.com",
	// "moa.be.xiaomi.com"
}

// func getCNAME(domain string) {
// 	var res Web
// 	res.Domain = domain
// 	dnsServer := []string{"180.76.76.76", "223.5.5.5", "8.8.8.8", "61.139.2.69"}
// 	res.CNAME, res.IP, res.Err = Dig(domain, dnsServer, "udp", 5)
// }

func getClient() *http.Client {
	tr := &http.Transport{
		TLSClientConfig:    &tls.Config{InsecureSkipVerify: true},
		DisableCompression: true,
		MaxIdleConns:       30,
		DisableKeepAlives:  true,
	}
	client := &http.Client{
		Transport: tr,
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			if len(via) > 5 {
				return errors.New("redirect more than 5 times")
			}
			return nil
		},
	}
	return client
}

func getAliveDomain(s []string) []string {
	color.Info.Prompt("Get subdomains of survival...")
	var alasList Set
	var aliveSet Set
	var res []string
	wg := WaitGroupWithCount{Count: 0}
	dnsServer := []string{"223.5.5.5", "180.76.76.76", "8.8.8.8", "61.139.2.69"}
	wg.Add(len(s))
	for _, v := range s {
		rateLimit <- true
		go func(v string) {
			defer func() {
				wg.Done()
				// wg.Count++
				// fmt.Printf("%d/%d\n", wg.Count, len(s))  // 进度条
			}()
			host := Dig(v, dnsServer, "udp", 5)
			<-rateLimit
			if len(host.CNAME) > 0 {
				alasList = append(alasList, host.CNAME...)
				cnameTLD := strings.Split(host.CNAME[len(host.CNAME)-1], ".")
				domainTLD := strings.Split(host.Domain, ".")
				// subdomain takeover
				if !SliceEqual(cnameTLD[len(cnameTLD)-2:], domainTLD[len(domainTLD)-2:]) {
					if len(host.IP) != 0 {
						// color.Info.Tips("%s's CNAME is %s.%s", host.Domain, strings.Join(cnameTLD[:len(cnameTLD)-2], "."), color.Bold.Text(strings.Join(cnameTLD[len(cnameTLD)-2:], ".")))
					} else {
						color.Warn.Tips("%s's CNAME is %s, May be taken over", host.Domain, color.Bold.Text(host.CNAME[len(host.CNAME)-1]))
					}
				}
			}
			if len(host.IP) > 0 {
				reg, _ := regexp.Compile(`^(127|10|(192\.168)|(172\.(1[6-9]|2\d|31)))\..*`)
				if reg.MatchString(host.IP[0]) {
					// Intranet IP
					// color.Info.Tips("%s A %v is Intranet IP", host.Domain, color.Bold.Text(host.IP[0]))
				} else {
					aliveSet = append(aliveSet, host.Domain)
				}
			}
		}(v)
	}
	wg.Wait()
	alasList = Uniq(alasList)
	for _, v := range aliveSet {
		if !alasList.Contains(v) {
			res = append(res, v)
		}
	}
	return res
}

var rateLimit chan bool = make(chan bool, 2)

func main() {
	// domain := "paypal.com"
	// s, _ := GetSubdomains(domain)
	// s = getAliveDomain(s)
	// fmt.Println(s)
	// wg := WaitGroupWithCount{}
	// wg.Count = 0
	// client := getClient()
	// for _, host := range s {
	// 	wg.Add(1)
	// 	go func(host string) {
	// 		defer func() {
	// 			wg.Done()
	// 			<-rateLimit
	// 		}()
	// 		html, _ := GetHTML(client, host)
	// 		fmt.Println(html)
	// 		OutputHTML(domain+".html", html)

	// 	}(host)
	// 	rateLimit <- true
	// }
	// close(rateLimit)
	// wg.Wait()
	//---------------------
	r, _ := GetSubdomains("baidu.com")
	fmt.Println(r)
	// fmt.Println(Google("c205.top"))
}
